[package]
name = "poly-manifold-spaces"
version = "0.1.0"
edition = "2021"

[dependencies]
poly-manifold-core = { path = "../poly-manifold-core" }
nalgebra = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
